### ISSUE TITLE
Condition (helper) inside can-EVENT doesn't work

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#1800]
in latest minor pre 2.3 code:

```HTML
<div can-click="{{#if canShowPopover}}togglePopover{{/if}}"></div>
```

causes an error:
```
Uncaught TypeError: Cannot read property 'compile' of undefined .../node_modules/can/view/stache/text_section.js 29 TypeError: Cannot read property 'compile' of undefined
```

it works in 2.2.6

**Comment by justinbmeyer** [comment]
I don't think this is valid. We can fix it, but the #if should go on the outside of the whole attribute.

**Comment by whitecolor** [comment]
Why not valid? It is usefull some times:

```HTML
<div can-click="{{#if shown}}hide{{else}}show{{if}}"></div>
```

outside `#if` doesn't work anyway yet.

**Comment by whitecolor** [comment]
I think this may be related https://github.com/bitovi/canjs/issues/1770

**Comment by whitecolor** [comment]
@daffl is it difficult to fix in minor?

**Comment by daffl** [comment]
Doesn't a helper just get used like

```html
<div can-click="{{#canShowPopover}}togglePopover{{/canShowPopover}}"></div>
```

Also your example does not have a closing `{{/if}}`.

**Comment by whitecolor** [comment]
@daffl it just a mistype, doesn't work any way

**Comment by whitecolor** [comment]
Are you going to fix this soon?

**Comment by matthewp** [comment]
Probably not soon, PRs welcome though.

**Comment by whitecolor** [comment]
@matthewp not sure where to look it.

**Comment by daffl** [comment]
I'll have a look next week. If this worked in 2.2 we should probably find out what changed.

**Comment by justinbmeyer** [comment]
We turned off processing in can.view.attrs to make it so we can switch between single binding and two way binding.

**Comment by beno** [comment]
This must have been something introduced between 2.2.6 and 2.2.7

My navigation component is now broken (I use SLIM and the ~ is short for {{ }})

    nav
     ul.nav.clearfix
       ~#actions
         li
           a href="#" can-click="{~.}" ~.

To avoid confusion, here's what this gets translated into:

    <nav>
      <ul class="nav clearfix">
        {{#actions}}
          <li><a can-click="{{.}}" href="#">{{.}}</a></li>
        {{/actions}}
      </ul>
    </nav>

This all works fine in 2.2.6, but fails in 2.2.7:

    scopeData.value.apply is not a function

**Comment by dylanrtt** [comment]
@beno This only applies to custom attributes defined with `can.view.attr` which I've brought up in basically a duplicate issue [here](https://github.com/bitovi/canjs/issues/1770#issuecomment-125701189).

What basically happens now is the `can.view.attr` callback just receives a string before processing. This is necessary to make the new references bindings work because the #-prefixed attributes need to see the raw string to determine whether to hook up a 1-way or 2-way binding. This probably would have been avoided if the references bindings were part of `can.Component` instead of a custom attribute pattern.

The probable resolution would be to modify existing custom attribute callbacks, particularly `can-EVENT`, to do the processing internally.

**Comment by beno** [comment]
Not sure I follow. Are you saying the behavior of the attributes (like can-EVENT) has been changed to accommodate  #-prefixed attributes? And is this considered a feature or a bug? If feature, how would one create the logic in my example from 2.3 onward?

To be sure, the 'actions'-array in my code is a simple list of strings with each string having a corresponding function in the viewModel. So I am not doing any custom attributes or anything like that.

**Comment by dylanrtt** [comment]
The behavior of registering a custom attribute callback with `can.view.attr` was changed so the #-prefixed attributes which are registered with `can.view.attr` (`/#[\w\.\-_]+/` pattern) can get the raw string instead of a processed one. This was a necessary feature to make it work with and now people are seeing the side effect. 

I was referring to what could be done to resolve it within the framework. Since `can-EVENT` is registered with `can.view.attr`, that's why this is a problem and the function defined for `can-EVENT` could be updated to process the string.

Justin also through out the [idea](https://github.com/bitovi/canjs/issues/1770#issuecomment-125376177) of making a special syntax for enforcing that the mustache code is processed before the attribute callback receives it, but I'm not sure I like that.

Unfortunately, I don't think there's anything you can do within the context of your app to fix this without adding unnecessary complexity.

**Comment by beno** [comment]
OK, thanks for the explanation, I get it now.

> Unfortunately, I don't think there's anything you can do within the context of your app to fix this without adding unnecessary complexity.

So there is no way to have any kind of dynamic custom attribute? That is quite the regression, don't think I have ever encountered something like this before. Besides, doesn't a 1-way vs 2-way binding only make sense in can-value attributes?

**Comment by matthewp** [comment]
Hold on, first this is a legitimate bug as it is a regression, no one is saying this is a "won't fix".  It's probably a hard thing to fix though, would you be ok if it was "opt in" so that you enabled it some how? That's my first thought.

It's probably possible to do what you want to do by changing can-click to read `.` from the scope.  This can definitely be fixed.

**Comment by beno** [comment]
Ah, it was unclear to me whether it was considered a bug or not. I think I'd rather have a special way to enable the new behavior and leave the existing functionality as is. But flipping this around would be the next best thing too I suppose.

Not sure what you meant by your last remark. Can you elaborate? Thanks.

**Comment by matthewp** [comment]
@beno before we discuss the fix it would be really awesome to get a minimal breaking test.  If you could submit a PR with a [breaking test here](https://github.com/bitovi/canjs/blob/master/view/bindings/bindings_test.js) we can discuss a fix.

**Comment by matthewp** [comment]
There's 2 things at play here; fixing can-EVENT probably pretty easy, but fixing it for all can.view.attrs would not be.

**Comment by justinbmeyer** [comment]
To be clear, a dynamic custom attribute was never intended to work. Just a happy accident. So it's a gray area if this is a bug or regression. 

However, we can still make it work by allowing can-value to make the attribute a template, running the template, and seeing the result.

**Comment by justinbmeyer** [comment]
I didn't want to make it part of component because other things can have viewModels. I want this to work for them as well.

**Comment by matthewp** [comment]
@justinbmeyer can't we just check for `{{foo}}` and then lookup `foo` in the scope?

**Comment by justinbmeyer** [comment]
Yes, but I think we could make "{{#mobile}}touch{{else}}click{{/}}" work too.

**Comment by whitecolor** [comment]
`"{{#mobile}}touch{{else}}click{{/}}"` I use such often or such pattern: 

`can-click="{{clickMethod}}"` where  `clickMethod: function(){this.attr('mobile') ? 'touch' : 'click"}`

**Comment by whitecolor** [comment]
Will it be fixed soon? The only thing that holds to migrate one of our projects to 2.3beta.

**Comment by dylanrtt** [comment]
@whitecolor The new [binding syntax](http://canjs.com/2.3-pre/docs/can.view.bindings.event.html) should allow this. I haven't tried it yet but you might be able to upgrade now.

```
<input type="button" ($click)="{{#if shown}}hide{{else}}show{{/if}}">
```

The nice thing is the binding behavior will be controlled on the left side allowing you to do all kinds of mustachy stuff in the attribute value.

**Comment by matthewp** [comment]
Yes, please try with 2.3-beta and let us know.

**Comment by justinbmeyer** [comment]
@whitecolor I don't think 2.3 supports this yet.  I never changed the behavior of custom attributes to not be processed.  However, reverting this change should be possible now.  Please revert it and let us know.  It would be good to get this in 2.3 while there's still time.  Thanks!

**Comment by whitecolor** [comment]
@dylanrtt @matthewp @justinbmeyer
I've checked on beta4 it doesn't work, error stack:
```
Potentially unhandled rejection [14] TypeError: Cannot read property 'compile' of undefined
    at can.extend.compile (.../node_modules/can/view/stache/text_section.js:29:32)
    at Object.parser.attrEnd (.../node_modules/can/view/stache/stache.js:216:47)
    at callAttrEnd (.../node_modules/can/view/parser/parser.js:285:11)
    at Function.HTMLParser.parseAttrs (.../node_modules/can/view/parser/parser.js:348:7)
    at parseStartTag (.../node_modules/can/view/parser/parser.js:112:15)
    at String.replace (native)
    at HTMLParser (.../node_modules/can/view/parser/parser.js:214:16)
    at stache (.../node_modules/can/view/stache/stache.js:122:3)
    at Object.can.view.register.fragRenderer (.../node_modules/can/view/stache/stache.js:349:11)
    at Function.can.extend.register.can.(anonymous function).$view.(anonymous function).renderFunc [as renderer] (.../node_modules/can/view/view.js:404:25)
```

**Comment by whitecolor** [comment]
What about this?

**Comment by justinbmeyer** [comment]
Did you try reverting? Does it work?

**Comment by whitecolor** [comment]
> Did you try reverting? Does it work?

What do you mean?

**Comment by justinbmeyer** [comment]
A few comments previous, I mentioned trying to revert the change that custom attrs are not processed.

**Comment by whitecolor** [comment]
the same result with an error

**Comment by justinbmeyer** [comment]
a test will speed up the process of getting this fixed.  What was the error?

**Comment by beno** [comment]
I made this test a while ago

https://github.com/bitovi/canjs/pull/1863

**Comment by justinbmeyer** [comment]
@beno thanks!

**Comment by whitecolor** [comment]
When is it going to be fixed?

**Comment by justinbmeyer** [comment]
@whitecolor what was the error you saw when you tried the above?  This isn't a super high priority fix for us.  We have it slated for 2.3.2.  But there's 20 or so other issues in this release.  Any help you can give will be greatly appreciated.

**Comment by justinbmeyer** [comment]
@whitecolor I changed the code, got no errors, and all tests passed, including the one submitted by @beno .  Can you confirm that you actually got an error?

**Comment by daffl** [comment]
Closed via #2066
